task:
  name: Windows
  windows_container:
    image: cirrusci/windowsservercore:cmake
  install_script:
    # - choco install -y winflexbison diffutils
    # - rename c:\ProgramData\chocolatey\bin\win_flex.exe flex.exe
    # - rename c:\ProgramData\chocolatey\bin\win_bison.exe bison.exe
    # - choco install -y visualstudio2019-workload-vctools --package-parameters "--includeOptional"
      - choco list --localonly
  build_script:
      - cd
      - set
      - cd "c:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Auxiliary/Build"
      - vcvarsall x64
      - set
      - msbuild pgsql.sln
#  test_script:
#    - cd src\tools\msvc && vcregress check
