task:
  name: Windows
  windows_container:
    dockerfile: ci/Dockerfile
  build_script:
      - cd "c:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Auxiliary/Build"
      - vcvarsall x64
      - echo on
      - cd C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build
      - set PATH=C:\strawberry\perl\bin;%PATH%
      - perl src/tools/msvc/mkvcbuild.pl
      - msbuild pgsql.sln
  test_script:
      - set PATH=C:\strawberry\perl\bin;%PATH%
      - perl src/tools/msvc/vcregress.pl check
